### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by Henrymistert123** [Download-Manager-Community/Download-Manager#28]
### Solution/Idea

Add sound effects for example:

- Play a sound when download completes
- Play a sound when download fails
- Play a sound when the download starts

This will help the user know when their download is ready instead of looking at the program

### Alternatives

none

### Windows Version

Windows 11 x64

**Comment by Soniczac7** [comment]
There is already a sound that plays when the download fails due to a message box which opens saying there is an error.
A sound would not be required when the download starts because the user would already know when the download starts because they would have started the download themselves.
However, playing a sound does sound like a good idea to notify the user that the download completed.
